repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.13.0" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--disable-error-code=import-untyped, --ignore-missing-imports]
