services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"  
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile  
    ports:
      - "8501:8501"  
    networks:
      - app-network
    environment:
      - FASTAPI_URL=http://fastapi:8000/classify 

networks:
  app-network:
    driver: bridge
